### ISSUE TITLE
Core goes off every 20 minutes

### ISSUE THREAD

**Issue by tlk** [tlk/beoplay-macos-remote-gui#10]
> my Core goes off every 20 minutes like when you press the power icon button located at the top left of the B&O app main screen. Looking at the device through the B&O app "now playing" screen, it does not show a usual off status but a "tunein" paused status instead. Very confusing and unusual. Note that the all lowercase "tunein" wording is coming from your tool when using the TuneIn Radio option. This "tunein" indicator is never shown when the product is controlled by the B&O App.
> I thought it could be a phantom code running on my Mac that could do that, but the device went off even after a Mac reboot.
> I restarted the product and after 20' it didn't go off, but I only played with sources and volume with the tool. I'll get back to you with more details when I'm able to reproduce the issue, but my feeling is that the Radio option may introduce some disorder somewhere.
> 

_Originally posted by @mbolo01 in https://github.com/tlk/beoplay-macos-remote-gui/issues/4#issuecomment-556493797_

**Comment by mbolo01** [comment]
This issue can be closed as it didn't occur again since I first reported it.
