### ISSUE TITLE
Application not seen in menu bar until app.title is set

### ISSUE THREAD

**Issue by mbolo01** [tlk/beoplay-macos-remote-gui#15]
I was not able to see the application item in the menu bar until I set the app.title to my preferred value. I guess it should have defaulted to "BeoplayRemote", but it didn't or something happened. 

I'll try to recreate with the latest code by wiping app.title

FYI: I have Bartender app running to enable me to see all menu items when there is not enough room.

**Comment by tlk** [comment]
Odd, it should already default to "BeoplayRemote". The app.title default can be remove like this:

```
bundleid=$(defaults read /Applications/BeoplayRemoteGUI.app/Contents/Info.plist CFBundleIdentifier)
defaults delete $bundleid app.title
```

**Comment by mbolo01** [comment]
my fault! I had the wrong Bartender option set for it. Sorry
