### ISSUE TITLE
Support for macOS Big Sur

### ISSUE THREAD

**Issue by madsthygesen** [tlk/beoplay-macos-remote-gui#25]
Hi 

Any chance to make the code combatibel with  MACos Big Sur?

Thanks.

**Comment by tlk** [comment]
Hi Mads

I am not sure if this is a question or a statement, but from what I can tell no changes are necessary in the code for it to work on macOS Big Sur Beta. Did you experience any issues?

Best regards,
  Thomas

**Comment by madsthygesen** [comment]
Yes, I did...

But I can run it with the newest version, thank you very much.

**Comment by tlk** [comment]
The app fails to start on the latest macOS Big Sur beta. I expect this issue will be solved by Apple before Big Sur is released.

There is a workaround described here: https://stackoverflow.com/questions/64366205/xcode-12-2-beta-3-big-sur-beta-10-throw-sigcont-for-swiftui-app/64375512#64375512
