### ISSUE TITLE
BeoSound Moment

### ISSUE THREAD

**Issue by mbolo01** [tlk/beoplay-macos-remote-gui#6]
Unfortunately the BeoSound Moment is not following the same exact schema than the other B&O products. Where volume control respond to the same commands, other actions are failing or not producing the expected results. 
It would be good to either inventory the differences and grey out some options when they are not compatible with the Moment (which is EOL, so we can guess it will never be aligned with other products), or learn about the differences and treat them as exceptions.

KR - Jérôme

**Comment by mbolo01** [comment]
Discovery.app brought to my attention that Beosound Moment is a using different service protocol/port than the Beoplay devices:
<img width="530" alt="screenshot_106" src="https://user-images.githubusercontent.com/57586871/69374754-0d463c80-0ca7-11ea-8b66-bb547f6830ca.png">

**Comment by tlk** [comment]
The trace in #26 revealed that the Moment did indeed listen on TCP port 80. It would be interesting to have a look at what is going over the wire when the device is remote controlled by something that works (e.g. the iOS app).

This guide may be useful https://wiki.wireshark.org/HowToDecrypt802.11

I believe the key is to power off the mobile phone, start data recording, and then power on the mobile. Not sure that turning flight mode on/off is enough.

**Comment by tlk** [comment]
Btw, I found this handbook https://beointegration.com/uploaded/EN-BeoLink-handbook-v1-9.pdf

From page 156:

<img width="939" alt="Screenshot 2020-09-24 at 17 28 40" src="https://user-images.githubusercontent.com/90870/94166358-7e3c1f00-fe8b-11ea-88ed-16ad597fb22d.png">

**Comment by mbolo01** [comment]
Your latest fix enables proper Moment control now (Sources & Radio), no need to look int the wire for this one now. Nevertheless, I'll have to do it to capture the Standby All command which would really be a good feature to your app.
You are doing much better than the latest 750€ remote which does not even control the Moment!

**Comment by tlk** [comment]
That is great news! I guess this issue can be closed now.

Got to give B&O credit for the design of the API that makes this possible. Thanks :)
